### PR TITLE
perf: remove smolstr

### PR DESCRIPTION
**Pull request by Boshen**
All source code are large strings, so the `SmolStr` optimization will never kick in

relates to #37

### CODE REVIEW

**Comment by Boshen** [comment]
Should probably change them to &str, let me try...

**Comment by Boshen** [comment]
👋 @ahabhgk

**Review by ahabhgk — APPROVED** [review]

**Comment by hardfist** [comment]
!bench

**Comment by hardfist** [comment]
seems not support bench 😭

**Comment by ahabhgk** [comment]
Maybe we can do the same on `RawSource`, `SourceMapSource`, and `OriginalSource`, use a more efficient structure instead of `String` to avoid the high overhead of cloning. (turbopack uses [`Rope`](https://github.com/vercel/turbo/blob/96cc535a2f2a4255aac7e2c1db347bd5ad470c1d/crates/turbo-tasks-fs/src/rope.rs#L22) for this)

**Comment by Boshen** [comment]
> Maybe we can do the same on `RawSource`, `SourceMapSource`, and `OriginalSource`, use a more efficient structure instead of `String` to avoid the high overhead of cloning. (turbopack uses [`Rope`](https://github.com/vercel/turbo/blob/96cc535a2f2a4255aac7e2c1db347bd5ad470c1d/crates/turbo-tasks-fs/src/rope.rs#L22) for this)

Interesting, thanks for sharing.

**Pull request merged**
